<?php

	namespace TutoMVC\WordPress\Core\Controller\Ajax;

	use _WP_Editors;
	use TutoMVC\WordPress\Core\Controller\Command\AjaxCommand;
	use function is_string;
	use function json_decode;
	use function json_encode;
	use function ob_get_clean;
	use function ob_start;
	use function stristr;
	use function wp_editor;
	use function wp_parse_args;
	use function wp_verify_nonce;

	class WPEditorAjaxCommand extends AjaxCommand
	{
		const NAME = "tutomvc_wpeditor";

		protected $_settings;

		public function execute()
		{
			if ( wp_verify_nonce( $_GET[ 'nonce' ], self::NAME ) )
			{
				add_action( 'before_wp_tiny_mce', array($this, "wpTinyMCE") );
				$args                    = array();
				$args[ 'textarea_name' ] = $_GET[ 'elementName' ];
				$args                    = wp_parse_args( $args, array(
					'wpautop'             => TRUE,
					'media_buttons'       => TRUE,
					'default_editor'      => '',
					'drag_drop_upload'    => FALSE,
					'textarea_rows'       => 20,
					'tabindex'            => '',
					'tabfocus_elements'   => ':prev,:next',
					'editor_css'          => '',
					'editor_class'        => '',
					'teeny'               => FALSE,
					'dfw'                 => FALSE,
					'_content_editor_dfw' => FALSE,
					'tinymce'             => TRUE,
					'quicktags'           => TRUE
				) );
				ob_start();
				wp_editor( $_REQUEST[ 'content' ], $_GET[ 'id' ], $args );
				$editor = ob_get_clean();
				ob_start();
				_WP_Editors::editor_js();
				$js = ob_get_clean();

				header( 'Content-type: application/json' );
				echo json_encode( array(
					"html"     => $editor,
					"js"       => $js,
					"settings" => $this->_settings
				) );
				exit;
			}

			die( "ERROR" );
		}

		public function wpTinyMCE( $settings )
		{
			$this->_settings = array_pop( $settings );
			foreach ( $this->_settings as $key => &$value )
			{
				if ( is_string( $value ) && stristr( $value, "{" ) !== FALSE )
				{
					$value = json_decode( $value );
				}
			}
		}

		public function register()
		{
			parent::register(); // TODO: Change the autogenerated stub
		}
	}
